version: '3.2'

services:
  app1.api:
    image: mservice/app1:${TAG:-latest}
    build:
      context: .
      dockerfile: dockerfile.WebApp1

  app2.api:
    image: mservice/app2:${TAG:-latest}
    build:
      context: .
      dockerfile: dockerfile.WebApp2
    depends_on:
      - app1.api

  app3.api:
    image: mservice/app3:${TAG:-latest}
    build:
      context: .
      dockerfile: dockerfile.WebApp3
    depends_on:
      - app2.api